  # Ensure pg gem is defined in your Gemfile

common: &common
  adapter: postgresql
  username: postgres
  encoding: SQL_ASCII
  template: template0
  pool: 5
  timeout: 5000



production:
  adapter: postgresql
  host: pgworld.cbxilpllykbb.us-west-2.rds.amazonaws.com
  port: 5432
  encoding: unicode
  database: miffmole
  pool: 5
  username: ward 
  password: zixpackt
